[package]
name = "memflow-native"
version = "0.2.0-beta11"
authors = ["Aurimas Blažulionis <0x60@pm.me>", "ko1N <ko1N1337@gmail.com>"]
edition = "2021"
rust-version = "1.65"
description = "System call based proxy-OS for memflow"
documentation = "https://docs.rs/memflow-native"
readme = "README.md"
homepage = "https://memflow.io"
repository = "https://github.com/memflow/memflow-native"
license = "MIT"
keywords = [ "memflow", "introspection", "memory", "dma" ]
categories = [ "api-bindings", "memory-management", "os" ]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
memflow = {features = ["plugins"], git = "https://github.com/roadkillsanta/memflow.git"}
log = "0.4"
libc = { version = "0.2.90" }
itertools = "0.10"
goblin = "^0.6"

windows = { version = "^0.46.0", features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp",
	"Win32_System_Diagnostics_Debug",
	"Win32_System_Threading",
	"Win32_System_ProcessStatus",
	"Win32_Security",
	"Win32_System_Memory"
] }

[features]
default = []
plugins = []
